# Generated by Django 4.0.4 on 2022-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc_fname', models.CharField(max_length=200, null=True)),
                ('otc_mname', models.CharField(max_length=200, null=True)),
                ('otc_lname', models.CharField(max_length=200, null=True)),
                ('otc_age', models.IntegerField(null=True)),
                ('otc_sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('otc_status', models.CharField(max_length=200, null=True)),
                ('otc_address', models.CharField(max_length=200, null=True)),
                ('otc_barangay', models.CharField(max_length=200, null=True)),
                ('otc_munincipality', models.CharField(max_length=200, null=True)),
                ('otc_email', models.EmailField(max_length=200, null=True)),
                ('otc_contact_number', models.IntegerField(null=True)),
            ],
        ),
    ]
