# Generated by Django 4.0.4 on 2022-06-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_address',
            new_name='SBP_address',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_age',
            new_name='SBP_age',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_barangay',
            new_name='SBP_barangay',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_contact_number',
            new_name='SBP_contact_number',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_email',
            new_name='SBP_email',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_fname',
            new_name='SBP_firstname',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_lname',
            new_name='SBP_lastname',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_mname',
            new_name='SBP_middlename',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_munincipality',
            new_name='SBP_munincipality',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_sex',
            new_name='SBP_sex',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='otc_status',
            new_name='SBP_status',
        ),
    ]
