# Generated by Django 4.0.4 on 2022-06-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0003_alter_personalinfo_sbp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations_ClassofVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccination_Category', models.CharField(choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Sinovac', 'Sinovac'), ('Sputnik', 'Sputnik'), ('Johnsons Janssen', 'Johnsons Janssen'), ('BioTech', 'BioTech'), ('Moderna', 'Moderna')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations_Doseofvaccineintake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vac_Immunity', models.CharField(choices=[('1st Dose', '1st Dose'), ('2nd Dose', '2nd Dose'), ('First Booster', 'First Booster'), ('Second Booster', 'Second Booster')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations_Takein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vac_Immunity', models.CharField(choices=[('1st Dose', '1st Dose'), ('2nd Dose', '2nd Dose'), ('First Booster', 'First Booster'), ('Second Booster', 'Second Booster')], max_length=200, null=True)),
                ('Vaccination_Category', models.CharField(choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Sinovac', 'Sinovac'), ('Sputnik', 'Sputnik'), ('Johnsons Janssen', 'Johnsons Janssen'), ('BioTech', 'BioTech'), ('Moderna', 'Moderna')], max_length=200, null=True)),
                ('Physical_mild_Effects', models.CharField(choices=[('Mild fever(Lagnat)', 'Mild fever(Lagnat)'), ('Chills(Pagkalamig)', 'Chills(Pagkalamig)'), ('Feeling tired(Pagod)', 'Feeling tired(Pagod)'), ('Headache(Pagsakit ng ulo)', 'Headache(Pagsakit ng ulo)'), ('Muscle and joint aches', 'Muscle and joint aches')], max_length=500, null=True)),
                ('Physical_Serious_Effects', models.CharField(choices=[('Mild fever(Lagnat)', 'Mild fever(Lagnat)'), ('Chills(Pagkalamig)', 'Chills(Pagkalamig)'), ('Feeling tired(Pagod)', 'Feeling tired(Pagod)'), ('Headache(Pagsakit ng ulo)', 'Headache(Pagsakit ng ulo)'), ('Muscle and joint aches', 'Muscle and joint aches')], max_length=500, null=True)),
                ('Mental_Effects', models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Locomotors Impairment(Pagkawalang balanse)', 'Locomotors Impairment(Pagkawalang balanse)'), ('Sleep Deprivation(Hirap sa Pagtulog)', 'Sleep Deprivation(Hirap sa Pagtulog)'), ('Loss of Memory and focus(Pagiging Malimutin)', 'Loss of Memory and focus(Pagiging Malimutin)'), ('Hallucinations', 'Hallucinations'), ('None', 'None')], max_length=1000, null=True)),
                ('Trigger_Past_Illness', models.CharField(max_length=1000, null=True)),
                ('Experience_Effects', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Intakedosevaccine_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SBP.vaccinations_doseofvaccineintake')),
                ('Personal_id_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SBP.personalinfo')),
                ('classofvaccine_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SBP.vaccinations_classofvaccine')),
            ],
        ),
    ]
