# Generated by Django 4.0.4 on 2022-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0004_vaccinations_classofvaccine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='SBP_age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SBP_contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinations_takein',
            name='Physical_Serious_Effects',
            field=models.CharField(choices=[('Difficulty breathing(Hirap sa Paghinga)', 'Difficulty breathing(Hirap sa Paghinga'), ('Swelling of your face and throat(Pamamaga ng Muka at Lalamunan)', 'Swelling of your face and throat(Pagmamaga ng Muka at Lalamunan'), ('A fast heartbeat(palpitate)', 'A fast heartbeat(palpitate)'), ('A bad rash all over your body(Pamamantal)', 'A bad rash all over your body(Pamamantal)'), ('None', 'None')], max_length=500, null=True),
        ),
    ]
