# Generated by Django 4.0.4 on 2022-06-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0005_alter_personalinfo_sbp_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations_not_decide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concern_One', models.CharField(choices=[('I have concerns about the vaccines side effects,long-term safety and efficacy', 'I have concerns about the vaccines side effects,long-term safety and efficacy'), ('I have religious reasons', 'I have religious reasons'), ('I do not believe it will be a solution for coronavirus disease', 'I do not believe it will be a solution for coronavirus disease'), ('I believe that it will have negative effects on my health', 'I believe that it will have negative effects on my health')], max_length=200, null=True)),
                ('Concern_Two', models.CharField(choices=[('If my doctor would approve', 'If my doctor would approve'), ('If my family would approve', 'If my family would approve'), ('I want to wait for a period to observe how other people react to the vaccine', 'I want to wait for a period to observe how other people react to the vaccine')], max_length=200, null=True)),
                ('Concern_Three', models.CharField(choices=[('I can’t go on my own.I have a physical limitation', 'I can’t go on my own.I have a physical limitation'), ('I am too busy to get vaccinated', 'I am too busy to get vaccinated'), ('I don’t know where to go to get vaccinated', 'I don’t know where to go to get vaccinated')], max_length=200, null=True)),
                ('Other_Concern_Reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('Personal_id_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SBP.personalinfo')),
            ],
        ),
    ]
