# Generated by Django 4.0.4 on 2022-06-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0007_registration_online_schedule_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_online_schedule_form',
            name='Online_Form_Seven',
            field=models.CharField(choices=[('Fever', 'Fever'), ('Cold', 'Cold'), ('Cough', 'Cough'), ('Shortness Of Breath', 'Shortness Of Breath'), ('Sore Throats', 'Soar Throats'), ('None', 'None')], max_length=100, null=True),
        ),
    ]
