# Generated by Django 4.0.4 on 2022-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0008_alter_registration_online_schedule_form_online_form_seven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinations_takein',
            name='Physical_mild_Effects',
            field=models.CharField(choices=[('Mild fever(Lagnat)', 'Mild fever(Lagnat)'), ('Chills(Pagkalamig)', 'Chills(Pagkalamig)'), ('Feeling tired(Pagod)', 'Feeling tired(Pagod)'), ('Headache(Pagsakit ng ulo)', 'Headache(Pagsakit ng ulo)'), ('Muscle and joint aches', 'Muscle and joint aches'), ('None', 'None')], max_length=500, null=True),
        ),
    ]
