# Generated by Django 4.0.4 on 2022-06-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0009_alter_vaccinations_takein_physical_mild_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_online_schedule_form',
            name='Vaccine_confirmation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Cancelled', 'Cancelled'), ('Second Booster', 'Second Booster')], max_length=200, null=True),
        ),
    ]
