# Generated by Django 4.0.4 on 2022-06-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0010_registration_online_schedule_form_vaccine_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinations_takein',
            name='date_vaccines',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
