# Generated by Django 4.0.4 on 2022-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0012_remove_vaccinations_takein_intakedosevaccine_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_address',
            new_name='otc_address',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_age',
            new_name='otc_age',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_barangay',
            new_name='otc_barangay',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_contact_number',
            new_name='otc_contact_number',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_email',
            new_name='otc_email',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_firstname',
            new_name='otc_firstname',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_lastname',
            new_name='otc_lastname',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_middlename',
            new_name='otc_middlename',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_status',
            new_name='otc_munincipality',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SBP_sex',
            new_name='otc_sex',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='SBP_munincipality',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='otc_status',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed'), ('Nonemployed', 'Nonemployed')], max_length=200, null=True),
        ),
    ]
