# Generated by Django 4.0.4 on 2022-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0013_rename_sbp_address_personalinfo_otc_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinations_takein',
            name='date_vaccines',
        ),
        migrations.AlterField(
            model_name='vaccinations_takein',
            name='date_created',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
