# Generated by Django 4.0.4 on 2022-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0014_remove_vaccinations_takein_date_vaccines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='otc_munincipality',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
