# Generated by Django 4.0.4 on 2022-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0015_alter_personalinfo_otc_munincipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='otc_sex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
