# Generated by Django 4.0.4 on 2022-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0016_alter_personalinfo_otc_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='otc_sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
