# Generated by Django 4.0.4 on 2022-06-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0021_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message_sbp',
        ),
    ]
