# Generated by Django 4.0.4 on 2022-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0022_rename_message_message_sbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinations_takein',
            name='Physical_Serious_Effects',
            field=models.CharField(choices=[('Difficulty breathing(Hirap sa Paghinga)', 'Difficulty breathing(Hirap sa Paghinga'), ('Swelling of your face(Pamamaga ng Muka)', 'Swelling of your face(Pagmamaga ng Muka'), ('Swelling of your throat(Pamamaga ng Lalamunan)', 'Swelling of your throat(Pagmamaga ng Lalamunan'), ('A fast heartbeat(palpitate)', 'A fast heartbeat(palpitate)'), ('A bad rash all over your body(Pamamantal)', 'A bad rash all over your body(Pamamantal)'), ('None', 'None')], max_length=500, null=True),
        ),
    ]
