# Generated by Django 4.0.4 on 2022-06-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0024_positive_effects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positive_effects',
            name='Positive_effects_three',
        ),
    ]
