# Generated by Django 4.0.4 on 2022-06-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0026_positive_effects_date_created_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration_Online_Schedule_Form',
        ),
    ]
