# Generated by Django 4.0.4 on 2022-06-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBP', '0027_delete_registration_online_schedule_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='otc_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
